//
//  JsonArrayStrings.swift
//  AFoundationUnitTesting
//
//  Created by Ihor Myroniuk on 01.10.2020.
//  Copyright Â© 2020 Ihor Myroniuk. All rights reserved.
//

import XCTest
import Foundation
@testable import AFoundation

class JsonArrayStringsUnitTesting: XCTestCase {
//
//    func testArrayStrings() {
//        let strings = ["string1", "string2", "string3"]
//        var array = JsonArray()
//        for string in strings {
//            array.append(string)
//        }
//
//        do {
//            let arrayStrings = try array.arrayStrings()
//            
//            XCTAssert(arrayStrings == strings, "Object returned unexpected arraySrings \"\(String(describing: arrayStrings))\" while arraySrings \"(\(String(describing: strings))\" is expected)")
//        } catch {
//            XCTFail("Unexpected error \(error) is thrown")
//        }
//    }
//    
//    func testNotArrayStrings() {
//        let notStrings: [JsonValue] = ["string1", true, "string3"]
//        var array = JsonArray()
//        for notString in notStrings {
//            array.append(notString)
//        }
//        
//        do {
//            let arrayStrings = try array.arrayStrings()
//            
//            XCTFail("Error \(JsonErrorNotArrayStrings.self) has to be thrown, but arrayStrings \"\(String(describing: arrayStrings))\" is returned")
//        } catch _ as JsonErrorNotArrayStrings {
//            
//        } catch {
//            XCTFail("Unexpected error \(error.self) is thrown")
//        }
//    }
//    
}
